server:
  port: 6002
spring:
  application:
    name: insurance-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: insurancedb
      
springdoc:
  api-docs:
    path: /news-docs
  swagger-ui:
    path: /swagger-ui.html