server:
  port: 6001
  
spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:mysql://localhost:3306/DRIVERDB?createDatabaseIfNotExist=true
    username: root
    password: Karumari*08
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
springdoc:
  api-docs:
    path: /news-docs
  swagger-ui:
    path: /swagger-ui.html